version: 0.1
phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - yarn install
  build:
    commands:
      - echo Build started on `date`
      - yarn build
artifacts:
  files:
    - '**/*'
  base-directory: 'build'
artifacts:
  secondary-artifacts:
    artifact1:
      base-directory: $CODEBUILD_SRC_DIR
      files:
        - '**/*'
    artifact2:
      base-directory: $CODEBUILD_SRC_DIR_Source2Artifact
      files:
        - '**/*'
