version: 0.2
phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - yarn install
  build:
    commands:
      - echo Build started on `date`
      - yarn build
artifacts:
  secondary-artifacts:
    artifact1:
      base-directory: $CODEBUILD_SRC_DIR
      files:
        - '**/*'
    artifact2:
      base-directory: $CODEBUILD_SRC_DIR_Build1Artifact
      files:
        - '**/*'
