AWSTemplateFormatVersion: 2010-09-09

Resources:

  AmplifyApp:
    Type: "AWS::Amplify::App"
    Properties:
      Name: DTE-CMC_Devops
      Repository: https://github.com/antheny-vf/DTE_CMC-Devops_Sandbox
      OauthToken: 409a427b1717976e126c513a000a917eecc64562
      BuildSpec: |-
        version: 0.1
        frontend:
          phases:
            preBuild:
              commands:
                - yarn install
            build:
              commands:
                - yarn run build
          artifacts:
            baseDirectory: build
            files:
              - '**/*'
          cache:
            paths:
              - node_modules/**/*


  MasterBranch:
    Type: AWS::Amplify::Branch
    Properties:
      BranchName: master
      AppId: !GetAtt AmplifyApp.AppId
      Description: Master Branch
      EnableAutoBuild: true

  DevelopBranch:
    Type: AWS::Amplify::Branch
    Properties:
      BranchName: develop
      AppId: !GetAtt AmplifyApp.AppId
      Description: Develop Branch
      EnableAutoBuild: true